--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-7岿-24-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "HR"."ORDERS" 
   (	"ORDERID" NUMBER(2,0), 
	"CUSTID" NUMBER(2,0), 
	"BOOKID" NUMBER(2,0), 
	"SALEPRICE" NUMBER(8,0), 
	"ORDERDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.ORDERS
SET DEFINE OFF;
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (1,1,1,6000,to_date('20/07/01','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (2,1,3,21000,to_date('20/07/03','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (3,2,5,8000,to_date('20/07/03','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (4,3,6,6000,to_date('20/07/04','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (5,4,7,20000,to_date('20/07/05','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (6,1,2,12000,to_date('20/07/07','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (7,4,8,13000,to_date('20/07/07','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (8,3,10,12000,to_date('20/07/08','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (9,2,10,7000,to_date('20/07/09','RR/MM/DD'));
Insert into HR.ORDERS (ORDERID,CUSTID,BOOKID,SALEPRICE,ORDERDATE) values (10,3,8,13000,to_date('20/07/10','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C006999
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C006999" ON "HR"."ORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "HR"."ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "HR"."ORDERS" ADD FOREIGN KEY ("CUSTID")
	  REFERENCES "HR"."CUSTOMER" ("CUSTID") ENABLE;
  ALTER TABLE "HR"."ORDERS" ADD FOREIGN KEY ("BOOKID")
	  REFERENCES "HR"."BOOK" ("BOOKID") ENABLE;
