--------------------------------------------------------
--  파일이 생성됨 - 목요일-7월-24-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "HR"."CUSTOMER" 
   (	"CUSTID" NUMBER(2,0), 
	"NAME" VARCHAR2(40 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.CUSTOMER
SET DEFINE OFF;
Insert into HR.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (1,'박지성','영국 맨체스터','000-5000-0001');
Insert into HR.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (2,'김연아','대한민국 서울','000-6000-0001');
Insert into HR.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (3,'장미란','대한민국 강원도','000-7000-0001');
Insert into HR.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (4,'추신수','미국 클리블랜드','000-8000-0001');
Insert into HR.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (5,'박세리','대한민국 대전',null);
--------------------------------------------------------
--  DDL for Index SYS_C006998
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C006998" ON "HR"."CUSTOMER" ("CUSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "HR"."CUSTOMER" ADD PRIMARY KEY ("CUSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
