--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-7岿-24-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IMPORTED_BOOK
--------------------------------------------------------

  CREATE TABLE "SCOTT"."IMPORTED_BOOK" 
   (	"BOOKID" NUMBER, 
	"BOOKNAME" VARCHAR2(40 BYTE), 
	"PUBLISHER" VARCHAR2(40 BYTE), 
	"PRICE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.IMPORTED_BOOK
SET DEFINE OFF;
Insert into SCOTT.IMPORTED_BOOK (BOOKID,BOOKNAME,PUBLISHER,PRICE) values (21,'Zen Golf','Pearson',12000);
Insert into SCOTT.IMPORTED_BOOK (BOOKID,BOOKNAME,PUBLISHER,PRICE) values (22,'Soccer Skills','Human Kinetics',15000);
