--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANSWER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ANSWER" 
   (	"ID" NUMBER(*,0), 
	"QUESTION_ID" NUMBER(*,0), 
	"CONTENT" CLOB, 
	"CREATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SCOTT.ANSWER
SET DEFINE OFF;
Insert into SCOTT.ANSWER (ID,QUESTION_ID,CREATE_DATE) values (1,1,to_date('25/07/29','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007072
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007072" ON "SCOTT"."ANSWER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ANSWER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."ANSWER" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ANSWER" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ANSWER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ANSWER" ADD FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SCOTT"."QUESTION" ("ID") ON DELETE CASCADE ENABLE;
